import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    paddingBottom: 24,
    height: "100%",
    justifyContent: "center",
    backgroundColor: "#1a1c1b",
  },
  chatButton: {
    width: "auto",
    paddingHorizontal: 16,
  },
  subtitle: {
    fontFamily: "Aeonik",
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    marginBottom: 16,
  },
  title: {
    fontSize: 32,
    fontFamily: "Aeonik",
    color: "#fff",
    textAlign: "center",
    marginBottom: 16,
  },
  input: {
    alignSelf: "center",
    fontSize: 16,
    borderColor: "#2a2e2e",
    borderWidth: 1.5,
    color: "#fff",
    padding: 16,
    marginBottom: 12,
    borderRadius: 16,
    fontFamily: "Aeonik",
    justifyContent: "center",
  },
  disabledInput: {
    borderColor: "#22241f",
    backgroundColor: "#22241f",
  },
  filledInput: {
    borderColor: "#3a9c4d",
    backgroundColor: "#1a1c1b",
  },
  emptyInput: {
    borderColor: "#444",
    backgroundColor: "#1a1c1b",
    borderStyle: "dashed",
  },
  inputText: {
    fontSize: 16,
    color: "#fff",
    fontFamily: "Aeonik",
  },
  disabledText: {
    color: "#555",
  },
  placeholderText: {
    color: "#aaa",
  },
  inputFocused: {
    borderColor: "#95ff77",
  },
  buttonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  backButton: {
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalContent: {
    width: "90%",
    height: "80%",
    backgroundColor: "#1a1c1b",
    borderRadius: 16,
    padding: 16,
    borderColor: "#2a2e2e",
    borderWidth: 1.5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "Aeonik",
    color: "#fff",
  },
  closeButton: {
    padding: 4,
  },
  searchInput: {
    backgroundColor: "#2a2e2e",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    color: "#fff",
    fontFamily: "Aeonik",
  },
  list: {
    flex: 1,
  },
  listItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#2a2e2e",
  },
  listItemText: {
    fontSize: 16,
    color: "#fff",
    fontFamily: "Aeonik",
  },
  listItemDescription: {
    fontSize: 12,
    color: "#aaa",
    fontFamily: "Aeonik",
    marginTop: 4,
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingOverlay: {
    position: 'absolute',
    zIndex: 1000,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(26, 28, 27, 0.8)',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#fff',
    fontFamily: 'Aeonik',
  },
  // New styles for detailed specifications
  detailedSpecsContainer: {
    width: "100%",
    marginTop: 20,
    marginBottom: 20,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: "#2a2e2e",
    overflow: "hidden",
  },
  // Instructions for manual editing
  instructionsContainer: {
    width: "90%",
    alignSelf: "center",
    marginVertical: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#2a2e2e",
  },
  instructionsText: {
    fontSize: 16,
    fontFamily: "Aeonik",
    color: "#fff",
    textAlign: "center",
    marginBottom: 4,
  },
  instructionsSubtext: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#95ff77",
    textAlign: "center",
  },
  specsTitleBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3e3e",
  },
  specsTitleText: {
    fontSize: 18,
    fontFamily: "Aeonik",
    color: "#95ff77",
    fontWeight: "bold",
  },
  specSectionHeader: {
    backgroundColor: "#333",
    padding: 12,
    marginTop: 8,
    marginBottom: 8,
  },
  specSectionTitle: {
    fontSize: 16,
    fontFamily: "Aeonik",
    color: "#fff",
    fontWeight: "bold",
  },
  specItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  specItemLabel: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#ddd",
    flex: 1,
  },
  specItemValue: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#95ff77",
    flex: 1,
    textAlign: "right",
  },
  colorItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  colorSwatch: {
    width: 24,
    height: 24,
    borderRadius: 12,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#fff",
  },
  colorName: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#fff",
  },
  recallItem: {
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#333",
    borderRadius: 8,
  },
  recallCampaign: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#95ff77",
    marginBottom: 8,
  },
  recallSummary: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#fff",
    marginBottom: 12,
  },
  recallDetails: {
    marginBottom: 8,
  },
  recallLabel: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#aaa",
    marginBottom: 4,
  },
  recallText: {
    fontSize: 14,
    fontFamily: "Aeonik",
    color: "#fff",
  },
});
