import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContainer: {
    backgroundColor: "#2a2e2e",
    borderRadius: 16,
    padding: 20,
    width: "100%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: "#444",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#444",
  },
  modalTitle: {
    fontSize: 22,
    fontFamily: "Aeonik",
    color: "#fff",
    textAlign: "center",
    flex: 1,
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#444",
    justifyContent: "center",
    alignItems: "center",
  },
  modalInput: {
    width: "100%",
    fontSize: 16,
    fontFamily: "Aeonik",
    backgroundColor: "#1a1c1b",
    color: "#fff",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#444",
  },
  modalButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 6,
  },
  cancelButton: {
    backgroundColor: "#444",
    borderWidth: 1,
    borderColor: "#555",
  },
  submitButton: {
    backgroundColor: "#95ff77",
  },
  cancelButtonText: {
    fontFamily: "Aeonik",
    fontSize: 16,
    color: "#fff",
    fontWeight: "500",
  },
  submitButtonText: {
    fontFamily: "Aeonik",
    fontSize: 16,
    color: "#1a1c1b",
    fontWeight: "600",
  },
});
